applications: []
# - name: guestbook
#   namespace: argocd
#   additionalLabels: {}
#   additionalAnnotations: {}
#   project: guestbook
#   source:
#     repoURL: https://github.com/argoproj/argocd-example-apps.git
#     targetRevision: HEAD
#     path: guestbook
#     directory:
#       recurse: true
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: guestbook
#   syncPolicy:
#     automated:
#       prune: false
#       selfHeal: false
